apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q64bgx1bw-nodejs 
  janus-idp.io/tekton: q64bgx1bw-nodejs
  backstage.io/kubernetes-id: q64bgx1bw-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q64bgx1bw-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml